export const DEFAULT_PIN_RADIUS = 10;
export const DEFAULT_PIN_DIAMETER = DEFAULT_PIN_RADIUS * 2;
export const DEFAULT_CIRCUIT_PADDING_X = 10;
export const DEFAULT_CIRCUIT_PINS_GAP = 7;
export const DEFAULT_WIRE_THICKNESS = 3;
